improvements: added guest user name for displaying off-platform users name
civis-vote/civis-api pull request #597
Opened 2021-06-17 07:22 UTC by BALAJI-BALA

2021-06-18 15:26 UTC, mikevic commented
@BALAJI-BALA - it's going to be hard for the UI to determine when to show either a user's name or a guest's name. Why don't we give them a field that will return that calculated?

2021-06-22 07:55 UTC, BALAJI-BALA commented
> @BALAJI-BALA - it's going to be hard for the UI to determine when to show either a user's name or a guest's name. Why don't we give them a field that will return that calculated?

@mikevic Added a new field will return the calculated name.

2021-06-22 12:33 UTC, mikevic requested changes
@BALAJI-BALA - minor change, you can merge this PR.

2021-06-22 12:33 UTC, mikevic commented on app/graphql/types/objects/consultation_response/base.rb
> +				field :user_name,													String, nil, null: true
```suggestion
				field :respondent_name,													String, nil, null: true
```

2021-06-22 12:36 UTC, merged